{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-ingress
spec:
  ingressClassName: {{ .Values.ingress.ClassName }}
  rules:
  {{- with .Values.ingress.hosts }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}