apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mi-nginx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-nginx
                port:
                  number: 80
    - host: mi-httpd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-httpd
                port:
                  number: 80